server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/auctions
spring.datasource.username=auctions
spring.datasource.password=auctions

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=auctions
spring.rabbitmq.password=auctions

logging.level.org.flywaydb=INFO
