export type NotificationType =
  | 'OUTBID'
  | 'AUCTION_WON'
  | 'AUCTION_LOST'
  | 'AUCTION_CLOSED'
  | 'AUCTION_SUSPENDED'
  | 'AUCTION_EXTENDED'
  | 'WATCHED_AUCTION_ENDING_SOON'
  | 'NEW_BID_ON_OWN_AUCTION';
