insert into users (email, password_hash, role)
select 'collector@archivebid.test', 'demo-hash', 'USER'
where not exists (select 1 from users where email = 'collector@archivebid.test');

insert into users (email, password_hash, role)
select 'curator@archivebid.test', 'demo-hash', 'USER'
where not exists (select 1 from users where email = 'curator@archivebid.test');

insert into users (email, password_hash, role)
select 'dealer@archivebid.test', 'demo-hash', 'USER'
where not exists (select 1 from users where email = 'dealer@archivebid.test');

insert into auctions (
  title, description, category_code, subcategory_code, creator_author, estimated_year, language_code,
  item_condition, authenticity_status, provenance, start_price, current_price, min_increment, status,
  start_time, end_time, anti_sniping_window_sec, anti_sniping_extend_sec, created_by, winner_id,
  winning_bid_id, final_price, closed_at, closed_reason, version, created_at, updated_at
)
values
  ('Prima editie Mihai Eminescu - Poezii', 'Exemplar de biblioteca privata, cu urme minime de uzura si coperta originala.', 'RARE_BOOKS', 'FIRST_EDITIONS', 'Mihai Eminescu', 1884, 'Romanian', 'VERY_GOOD', 'VERIFIED', 'Colectie privata din Iasi.', 1200.00, 1200.00, 50.00, 'RUNNING', now() - interval '2 days', now() + interval '4 days', 120, 30, (select id from users where email = 'collector@archivebid.test'), null, null, null, null, null, 0, now() - interval '5 days', now() - interval '2 hours'),
  ('Editie limitata Tudor Arghezi', 'Volum numerotat din tiraj restrans, pastrat in conditii foarte bune.', 'RARE_BOOKS', 'LIMITED_EDITIONS', 'Tudor Arghezi', 1931, 'Romanian', 'EXCELLENT', 'VERIFIED', 'Fond documentar mostenit din biblioteca familiei.', 900.00, 900.00, 40.00, 'DRAFT', null, now() + interval '8 days', 120, 30, (select id from users where email = 'curator@archivebid.test'), null, null, null, null, null, 0, now() - interval '4 days', now() - interval '4 days'),
  ('Exemplar semnat de Mircea Eliade', 'Semnatura autorului pe pagina de titlu, cu dedicatie scurta.', 'RARE_BOOKS', 'SIGNED_COPIES', 'Mircea Eliade', 1936, 'Romanian', 'GOOD', 'IN_REVIEW', 'Achizitionat de la un anticariat bucurestean.', 1500.00, 1500.00, 75.00, 'RUNNING', now() - interval '1 day', now() + interval '2 days', 120, 30, (select id from users where email = 'dealer@archivebid.test'), null, null, null, null, null, 0, now() - interval '3 days', now() - interval '1 hour'),
  ('Carte bisericeasca de secol XIX', 'Tiparitura religioasa cu xilogravuri si insemnari de proprietate.', 'RARE_BOOKS', 'ANTIQUE_BOOKS', 'Tipografia Mitropoliei', 1827, 'Romanian', 'FRAGILE', 'UNVERIFIED', 'Provenienta dintr-o parohie rurala.', 700.00, 700.00, 30.00, 'ENDED', now() - interval '10 days', now() - interval '2 days', 120, 30, (select id from users where email = 'collector@archivebid.test'), null, null, 700.00, now() - interval '2 days', 'EXPIRED', 0, now() - interval '14 days', now() - interval '2 days'),
  ('Album de arta interbelica - Bucuresti', 'Album ilustrat cu reproduceri si comentarii curatoriale.', 'RARE_BOOKS', 'ART_ALBUMS', 'Octav Bancila', 1929, 'French', 'GOOD', 'VERIFIED', 'Arhiva de familie, Bucuresti.', 650.00, 650.00, 25.00, 'DRAFT', null, now() + interval '12 days', 120, 30, (select id from users where email = 'curator@archivebid.test'), null, null, null, null, null, 0, now() - interval '2 days', now() - interval '2 days'),

  ('Manuscris poetic simbolist', 'Caiet manuscris cu corecturi succesive si adnotari marginale.', 'MANUSCRIPTS', 'LITERARY_MANUSCRIPTS', 'Alexandru Macedonski', 1902, 'Romanian', 'GOOD', 'IN_REVIEW', 'Recuperat dintr-o colectie particulara.', 1800.00, 1800.00, 80.00, 'RUNNING', now() - interval '3 days', now() + interval '5 days', 120, 30, (select id from users where email = 'curator@archivebid.test'), null, null, null, null, null, 0, now() - interval '6 days', now() - interval '2 hours'),
  ('Cronica manuscrisa de epoca', 'Document istoric manuscris, cu filigran identificabil.', 'MANUSCRIPTS', 'HISTORICAL_MANUSCRIPTS', 'Anonim', 1815, 'Romanian', 'FRAGILE', 'VERIFIED', 'Fond arhivistic privat din Transilvania.', 2100.00, 2100.00, 100.00, 'DRAFT', null, now() + interval '9 days', 120, 30, (select id from users where email = 'dealer@archivebid.test'), null, null, null, null, null, 0, now() - interval '5 days', now() - interval '5 days'),
  ('Jurnal personal de front', 'Insemnari zilnice si schite rapide realizate in campanie.', 'MANUSCRIPTS', 'PERSONAL_NOTES', 'Lt. Nicolae Popescu', 1917, 'Romanian', 'VERY_GOOD', 'VERIFIED', 'Mostenire familiala, Brasov.', 1300.00, 1300.00, 60.00, 'RUNNING', now() - interval '6 hours', now() + interval '36 hours', 120, 30, (select id from users where email = 'collector@archivebid.test'), null, null, null, null, null, 0, now() - interval '4 days', now() - interval '30 minutes'),
  ('Scrisoare originala catre un editor francez', 'Corespondenta literara cu semnatura si plic original.', 'MANUSCRIPTS', 'ORIGINAL_LETTERS', 'Panait Istrati', 1925, 'French', 'GOOD', 'VERIFIED', 'Provenienta dintr-o colectie pariziana.', 950.00, 950.00, 45.00, 'ENDED', now() - interval '11 days', now() - interval '3 days', 120, 30, (select id from users where email = 'curator@archivebid.test'), null, null, 950.00, now() - interval '3 days', 'EXPIRED', 0, now() - interval '13 days', now() - interval '3 days'),
  ('Caiet de note diplomatice', 'Carnet cu notite de protocol si nume proprii de epoca.', 'MANUSCRIPTS', 'PERSONAL_NOTES', 'Diplomat anonim', 1938, 'French', 'FAIR', 'UNVERIFIED', 'Achizitie dintr-un lot documentar mixt.', 620.00, 620.00, 25.00, 'DRAFT', null, now() + interval '6 days', 120, 30, (select id from users where email = 'dealer@archivebid.test'), null, null, null, null, null, 0, now() - interval '3 days', now() - interval '3 days'),

  ('Decret administrativ cu sigiliu uscat', 'Act oficial cu semnatura si amprenta de sigiliu partial conservata.', 'HISTORICAL_DOCUMENTS', 'OFFICIAL_ACTS', 'Administratia Principatelor Unite', 1862, 'Romanian', 'GOOD', 'VERIFIED', 'Colectionat dintr-o arhiva boiereasca.', 1700.00, 1700.00, 75.00, 'RUNNING', now() - interval '4 days', now() + interval '1 day', 120, 30, (select id from users where email = 'collector@archivebid.test'), null, null, null, null, null, 0, now() - interval '7 days', now() - interval '20 minutes'),
  ('Proclamatie politica de campanie', 'Tipar politic cu adnotari si completari manuscrise.', 'HISTORICAL_DOCUMENTS', 'POLITICAL_DOCUMENTS', 'Comitet electoral local', 1928, 'Romanian', 'FAIR', 'IN_REVIEW', 'Gasit intr-o arhiva de partid dezafectata.', 880.00, 880.00, 35.00, 'DRAFT', null, now() + interval '10 days', 120, 30, (select id from users where email = 'curator@archivebid.test'), null, null, null, null, null, 0, now() - interval '6 days', now() - interval '6 days'),
  ('Ordin militar de mobilizare', 'Document militar semnat si numerotat, cu stampila unitatii.', 'HISTORICAL_DOCUMENTS', 'MILITARY_DOCUMENTS', 'Ministerul de Razboi', 1916, 'Romanian', 'VERY_GOOD', 'VERIFIED', 'Provenienta din colectie privata, Cluj.', 1450.00, 1450.00, 70.00, 'RUNNING', now() - interval '8 hours', now() + interval '3 days', 120, 30, (select id from users where email = 'dealer@archivebid.test'), null, null, null, null, null, 0, now() - interval '2 days', now() - interval '45 minutes'),
  ('Diploma nobiliara cu blazon', 'Pergament cu elemente heraldice si urme de ceara rosie.', 'HISTORICAL_DOCUMENTS', 'ROYAL_NOBLE_DOCUMENTS', 'Cancelaria regala', 1784, 'Latin', 'FRAGILE', 'VERIFIED', 'Fond familial transilvanean.', 2600.00, 2600.00, 120.00, 'ENDED', now() - interval '15 days', now() - interval '4 days', 120, 30, (select id from users where email = 'collector@archivebid.test'), null, null, 2600.00, now() - interval '4 days', 'EXPIRED', 0, now() - interval '18 days', now() - interval '4 days'),
  ('Autorizatie comerciala de inceput de secol XX', 'Document municipal cu semnaturi multiple si antet original.', 'HISTORICAL_DOCUMENTS', 'OFFICIAL_ACTS', 'Primaria Capitalei', 1908, 'Romanian', 'GOOD', 'UNVERIFIED', 'Lot achizitionat din arhiva unui notar.', 540.00, 540.00, 20.00, 'DRAFT', null, now() + interval '7 days', 120, 30, (select id from users where email = 'curator@archivebid.test'), null, null, null, null, null, 0, now() - interval '3 days', now() - interval '3 days'),

  ('Harta veche a Moldovei', 'Gravura colorata manual, cu margini largi si cartus decorativ.', 'MAPS_AND_ATLASES', 'ANTIQUE_MAPS', 'Guillaume Delisle', 1718, 'French', 'GOOD', 'VERIFIED', 'Colectionata in Belgia, importata in 1998.', 2300.00, 2300.00, 110.00, 'RUNNING', now() - interval '1 day', now() + interval '6 days', 120, 30, (select id from users where email = 'dealer@archivebid.test'), null, null, null, null, null, 0, now() - interval '6 days', now() - interval '1 hour'),
  ('Atlas scolar de geografie istorica', 'Atlas complet cu planse color si legatura originala.', 'MAPS_AND_ATLASES', 'ATLASES', 'Institut Geografic', 1899, 'German', 'VERY_GOOD', 'VERIFIED', 'Biblioteca particulara de profesor universitar.', 980.00, 980.00, 40.00, 'DRAFT', null, now() + interval '11 days', 120, 30, (select id from users where email = 'collector@archivebid.test'), null, null, null, null, null, 0, now() - interval '4 days', now() - interval '4 days'),
  ('Plan urbanistic al Bucurestiului', 'Plan pliabil cu marcaje administrative si zone comerciale.', 'MAPS_AND_ATLASES', 'URBAN_PLANS', 'Serviciul Tehnic Bucuresti', 1935, 'Romanian', 'GOOD', 'IN_REVIEW', 'Arhiva unui fost urbanist.', 1150.00, 1150.00, 55.00, 'RUNNING', now() - interval '10 hours', now() + interval '28 hours', 120, 30, (select id from users where email = 'curator@archivebid.test'), null, null, null, null, null, 0, now() - interval '3 days', now() - interval '20 minutes'),
  ('Harta militara a Dobrogei', 'Editie de campanie cu semne topografice si plieri de lucru.', 'MAPS_AND_ATLASES', 'MILITARY_MAPS', 'Statul Major', 1917, 'Romanian', 'FAIR', 'VERIFIED', 'Lot provenit dintr-o colectie de istorie militara.', 1600.00, 1600.00, 75.00, 'ENDED', now() - interval '12 days', now() - interval '2 days', 120, 30, (select id from users where email = 'dealer@archivebid.test'), null, null, 1600.00, now() - interval '2 days', 'EXPIRED', 0, now() - interval '14 days', now() - interval '2 days'),
  ('Harta turistica a Carpatilor', 'Tipar de inceput de secol XX cu trasee montane marcate manual.', 'MAPS_AND_ATLASES', 'ANTIQUE_MAPS', 'Clubul Turistic Roman', 1932, 'Romanian', 'GOOD', 'UNVERIFIED', 'Achizitionata din lot mixt de papetarie veche.', 420.00, 420.00, 20.00, 'DRAFT', null, now() + interval '5 days', 120, 30, (select id from users where email = 'collector@archivebid.test'), null, null, null, null, null, 0, now() - interval '2 days', now() - interval '2 days'),

  ('Fotografie istorica a Calea Victoriei', 'Print albuminat montat pe carton, cu inscriptie de atelier.', 'PHOTOGRAPHS_AND_VISUAL_ARCHIVES', 'HISTORICAL_PHOTOGRAPHS', 'Franz Duschek', 1889, 'Romanian', 'GOOD', 'VERIFIED', 'Fond de fotografie urbana, Bucuresti.', 1250.00, 1250.00, 60.00, 'RUNNING', now() - interval '2 days', now() + interval '5 days', 120, 30, (select id from users where email = 'curator@archivebid.test'), null, null, null, null, null, 0, now() - interval '5 days', now() - interval '1 hour'),
  ('Portret de atelier al unui avocat interbelic', 'Fotografie sepia cu stampila fotografului pe verso.', 'PHOTOGRAPHS_AND_VISUAL_ARCHIVES', 'PORTRAITS', 'Atelier Foto Splendid', 1931, 'Romanian', 'VERY_GOOD', 'IN_REVIEW', 'Provenienta de familie, Ploiesti.', 540.00, 540.00, 25.00, 'DRAFT', null, now() + interval '9 days', 120, 30, (select id from users where email = 'collector@archivebid.test'), null, null, null, null, null, 0, now() - interval '4 days', now() - interval '4 days'),
  ('Album de familie din perioada Regatului', 'Album complet cu 42 de fotografii si note manuscrise.', 'PHOTOGRAPHS_AND_VISUAL_ARCHIVES', 'ARCHIVE_ALBUMS', 'Familia Ionescu', 1912, 'Romanian', 'GOOD', 'VERIFIED', 'Pastrat in aceeasi familie pana in prezent.', 1900.00, 1900.00, 90.00, 'RUNNING', now() - interval '5 hours', now() + interval '2 days', 120, 30, (select id from users where email = 'dealer@archivebid.test'), null, null, null, null, null, 0, now() - interval '3 days', now() - interval '10 minutes'),
  ('Carte postala ilustrata - Sinaia', 'Piesa circulata, cu timbru si stampila postala lizibila.', 'PHOTOGRAPHS_AND_VISUAL_ARCHIVES', 'POSTCARDS', 'Editura Socec', 1906, 'French', 'FAIR', 'UNVERIFIED', 'Achizitie recenta dintr-o colectie de cartofilie.', 180.00, 180.00, 10.00, 'ENDED', now() - interval '9 days', now() - interval '1 day', 120, 30, (select id from users where email = 'curator@archivebid.test'), null, null, 180.00, now() - interval '1 day', 'EXPIRED', 0, now() - interval '10 days', now() - interval '1 day'),
  ('Lot de fotografii feroviare', 'Set de 8 fotografii de epoca cu locomotive si gari regionale.', 'PHOTOGRAPHS_AND_VISUAL_ARCHIVES', 'HISTORICAL_PHOTOGRAPHS', 'Autor necunoscut', 1922, 'Romanian', 'GOOD', 'IN_REVIEW', 'Licitatie anterioara de memorabilia industriala.', 760.00, 760.00, 30.00, 'DRAFT', null, now() + interval '6 days', 120, 30, (select id from users where email = 'dealer@archivebid.test'), null, null, null, null, null, 0, now() - interval '2 days', now() - interval '2 days'),

  ('Ziar despre Unirea Principatelor', 'Numar vechi cu stiri politice si reclama tipografica originala.', 'COLLECTIBLE_PRINTS', 'NEWSPAPERS', 'Tipografia Nationala', 1859, 'Romanian', 'FRAGILE', 'VERIFIED', 'Fond achizitionat de la casa de licitatii regionala.', 1350.00, 1350.00, 60.00, 'RUNNING', now() - interval '3 days', now() + interval '4 days', 120, 30, (select id from users where email = 'collector@archivebid.test'), null, null, null, null, null, 0, now() - interval '6 days', now() - interval '40 minutes'),
  ('Revista literara avangardista', 'Exemplar complet, cu ilustratii si reclame specifice perioadei.', 'COLLECTIBLE_PRINTS', 'RARE_MAGAZINES', 'Redactia Integral', 1926, 'Romanian', 'GOOD', 'VERIFIED', 'Biblioteca particulara de istorie literara.', 620.00, 620.00, 25.00, 'DRAFT', null, now() + interval '8 days', 120, 30, (select id from users where email = 'curator@archivebid.test'), null, null, null, null, null, 0, now() - interval '4 days', now() - interval '4 days'),
  ('Afis de teatru - premiera interbelica', 'Afis original tiparit color, cu mici lipsuri pe margine.', 'COLLECTIBLE_PRINTS', 'POSTERS', 'Teatrul National', 1934, 'Romanian', 'FAIR', 'IN_REVIEW', 'Salvat dintr-un depozit de recuzita.', 880.00, 880.00, 35.00, 'RUNNING', now() - interval '9 hours', now() + interval '30 hours', 120, 30, (select id from users where email = 'dealer@archivebid.test'), null, null, null, null, null, 0, now() - interval '3 days', now() - interval '15 minutes'),
  ('Program de opera cu distributie originala', 'Brosura de sala cu adnotari ale unui spectator contemporan.', 'COLLECTIBLE_PRINTS', 'EVENT_PROGRAMS', 'Opera Romana', 1921, 'Romanian', 'VERY_GOOD', 'UNVERIFIED', 'Colectie privata de memorabilia culturala.', 310.00, 310.00, 15.00, 'ENDED', now() - interval '8 days', now() - interval '18 hours', 120, 30, (select id from users where email = 'collector@archivebid.test'), null, null, 310.00, now() - interval '18 hours', 'EXPIRED', 0, now() - interval '9 days', now() - interval '18 hours'),
  ('Supliment ilustrat de expozitie universala', 'Publicatie promotionala cu pliante si gravuri tehnice.', 'COLLECTIBLE_PRINTS', 'RARE_MAGAZINES', 'Comitetul Expozitional', 1900, 'French', 'GOOD', 'VERIFIED', 'Lot provenit din arhiva unei familii de ingineri.', 470.00, 470.00, 20.00, 'DRAFT', null, now() + interval '7 days', 120, 30, (select id from users where email = 'curator@archivebid.test'), null, null, null, null, null, 0, now() - interval '3 days', now() - interval '3 days'),

  ('Teza universitara de medicina', 'Lucrare academica legata manual, cu aprobari si semnaturi oficiale.', 'SCIENTIFIC_AND_ACADEMIC_DOCUMENTS', 'ACADEMIC_PAPERS', 'Dr. Petre Georgescu', 1898, 'French', 'VERY_GOOD', 'VERIFIED', 'Fond medical universitar dezafectat.', 1420.00, 1420.00, 65.00, 'RUNNING', now() - interval '2 days', now() + interval '5 days', 120, 30, (select id from users where email = 'dealer@archivebid.test'), null, null, null, null, null, 0, now() - interval '5 days', now() - interval '30 minutes'),
  ('Caiet de laborator chimic', 'Carnet cu formule, observatii si pete de lucru specifice.', 'SCIENTIFIC_AND_ACADEMIC_DOCUMENTS', 'RESEARCH_NOTES', 'Prof. C. I. Istrati', 1904, 'Romanian', 'GOOD', 'IN_REVIEW', 'Recuperat din arhiva unui institut tehnic.', 990.00, 990.00, 45.00, 'DRAFT', null, now() + interval '10 days', 120, 30, (select id from users where email = 'collector@archivebid.test'), null, null, null, null, null, 0, now() - interval '4 days', now() - interval '4 days'),
  ('Brevet de inventie pentru aparat optic', 'Document tehnic cu planse anexate si stampile de depunere.', 'SCIENTIFIC_AND_ACADEMIC_DOCUMENTS', 'PATENTS', 'Ing. Gheorghe Marinescu', 1937, 'Romanian', 'GOOD', 'VERIFIED', 'Licitatie de profil tehnic, lot secundar.', 1650.00, 1650.00, 80.00, 'RUNNING', now() - interval '12 hours', now() + interval '42 hours', 120, 30, (select id from users where email = 'curator@archivebid.test'), null, null, null, null, null, 0, now() - interval '2 days', now() - interval '15 minutes'),
  ('Publicatie stiintifica rara despre geologie', 'Fascicula completa cu planse pliate si notite de lectura.', 'SCIENTIFIC_AND_ACADEMIC_DOCUMENTS', 'RARE_PUBLICATIONS', 'Societatea Geologica', 1887, 'German', 'FAIR', 'UNVERIFIED', 'Achizitionata dintr-o biblioteca universitara privata.', 780.00, 780.00, 30.00, 'ENDED', now() - interval '10 days', now() - interval '2 days', 120, 30, (select id from users where email = 'dealer@archivebid.test'), null, null, 780.00, now() - interval '2 days', 'EXPIRED', 0, now() - interval '11 days', now() - interval '2 days'),
  ('Lot de prelegeri academice dactilografiate', 'Set de cursuri si note de seminar din perioada interbelica.', 'SCIENTIFIC_AND_ACADEMIC_DOCUMENTS', 'ACADEMIC_PAPERS', 'Facultatea de Litere', 1933, 'Romanian', 'GOOD', 'IN_REVIEW', 'Arhiva mostenita de la un profesor universitar.', 520.00, 520.00, 20.00, 'DRAFT', null, now() + interval '6 days', 120, 30, (select id from users where email = 'collector@archivebid.test'), null, null, null, null, null, 0, now() - interval '2 days', now() - interval '2 days');
