-- Generated by scripts/generate_thematic_demo_assets.mjs

delete from auction_images where image_url like '/demo-images/%';

update auctions set
  title = 'First Edition Mihai Eminescu - Poems',
  description = 'Private library copy with minimal wear and the original publisher binding.',
  provenance = 'Private library collection from Iasi.'
where title = 'Prima editie Mihai Eminescu - Poezii';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/first-edition-mihai-eminescu-poems.svg', 0
from auctions a
where a.title = 'First Edition Mihai Eminescu - Poems'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/first-edition-mihai-eminescu-poems.svg'
  );

update auctions set
  title = 'Limited Tudor Arghezi Edition',
  description = 'Numbered copy from a reduced print run, preserved in excellent condition.',
  provenance = 'Inherited documentary holding from a family library.'
where title = 'Editie limitata Tudor Arghezi';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/limited-tudor-arghezi-edition.svg', 0
from auctions a
where a.title = 'Limited Tudor Arghezi Edition'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/limited-tudor-arghezi-edition.svg'
  );

update auctions set
  title = 'Signed Copy by Mircea Eliade',
  description = 'Author signature on the title page with a short handwritten dedication.',
  provenance = 'Acquired from an antiquarian bookshop in Bucharest.'
where title = 'Exemplar semnat de Mircea Eliade';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/signed-copy-mircea-eliade.svg', 0
from auctions a
where a.title = 'Signed Copy by Mircea Eliade'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/signed-copy-mircea-eliade.svg'
  );

update auctions set
  title = '19th Century Church Book',
  description = 'Religious printed volume with woodcut illustrations and ownership notes.',
  provenance = 'Sourced from a rural parish archive.'
where title = 'Carte bisericeasca de secol XIX';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/19th-century-church-book.svg', 0
from auctions a
where a.title = '19th Century Church Book'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/19th-century-church-book.svg'
  );

update auctions set
  title = 'Interwar Art Album - Bucharest',
  description = 'Illustrated album with curated reproductions and commentary from the period.',
  provenance = 'Family archive, Bucharest.'
where title = 'Album de arta interbelica - Bucuresti';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/interwar-art-album-bucharest.svg', 0
from auctions a
where a.title = 'Interwar Art Album - Bucharest'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/interwar-art-album-bucharest.svg'
  );

update auctions set
  title = 'Symbolist Poetic Manuscript',
  description = 'Handwritten notebook with layered revisions and marginal annotations.',
  provenance = 'Recovered from a private literary collection.'
where title = 'Manuscris poetic simbolist';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/symbolist-poetic-manuscript.svg', 0
from auctions a
where a.title = 'Symbolist Poetic Manuscript'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/symbolist-poetic-manuscript.svg'
  );

update auctions set
  title = 'Period Handwritten Chronicle',
  description = 'Historical manuscript with an identifiable watermark and archival paper stock.',
  provenance = 'Private archival holding from Transylvania.'
where title = 'Cronica manuscrisa de epoca';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/period-handwritten-chronicle.svg', 0
from auctions a
where a.title = 'Period Handwritten Chronicle'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/period-handwritten-chronicle.svg'
  );

update auctions set
  title = 'Personal Frontline Diary',
  description = 'Daily wartime notes with rapid sketches executed in campaign conditions.',
  provenance = 'Inherited by the same family in Brasov.'
where title = 'Jurnal personal de front';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/personal-frontline-diary.svg', 0
from auctions a
where a.title = 'Personal Frontline Diary'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/personal-frontline-diary.svg'
  );

update auctions set
  title = 'Original Letter to a French Publisher',
  description = 'Literary correspondence with signature and original mailing envelope.',
  provenance = 'From a Parisian private collection.'
where title = 'Scrisoare originala catre un editor francez';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/original-letter-french-publisher.svg', 0
from auctions a
where a.title = 'Original Letter to a French Publisher'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/original-letter-french-publisher.svg'
  );

update auctions set
  title = 'Diplomatic Notes Notebook',
  description = 'Pocket notebook with protocol notes and period proper names.',
  provenance = 'Acquired as part of a mixed documentary lot.'
where title = 'Caiet de note diplomatice';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/diplomatic-notes-notebook.svg', 0
from auctions a
where a.title = 'Diplomatic Notes Notebook'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/diplomatic-notes-notebook.svg'
  );

update auctions set
  title = 'Administrative Decree with Dry Seal',
  description = 'Official act with signature and a partially preserved embossed seal.',
  provenance = 'Collected from a boyar family archive.'
where title = 'Decret administrativ cu sigiliu uscat';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/administrative-decree-dry-seal.svg', 0
from auctions a
where a.title = 'Administrative Decree with Dry Seal'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/administrative-decree-dry-seal.svg'
  );

update auctions set
  title = 'Political Campaign Proclamation',
  description = 'Political broadside with handwritten amendments and contextual notes.',
  provenance = 'Recovered from a decommissioned party archive.'
where title = 'Proclamatie politica de campanie';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/political-campaign-proclamation.svg', 0
from auctions a
where a.title = 'Political Campaign Proclamation'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/political-campaign-proclamation.svg'
  );

update auctions set
  title = 'Military Mobilization Order',
  description = 'Signed military order with registry numbering and unit stamp.',
  provenance = 'Private military-history collection, Cluj.'
where title = 'Ordin militar de mobilizare';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/military-mobilization-order.svg', 0
from auctions a
where a.title = 'Military Mobilization Order'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/military-mobilization-order.svg'
  );

update auctions set
  title = 'Noble Diploma with Heraldic Arms',
  description = 'Parchment charter with heraldic imagery and traces of red sealing wax.',
  provenance = 'Transylvanian family holding.'
where title = 'Diploma nobiliara cu blazon';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/noble-diploma-heraldic-arms.svg', 0
from auctions a
where a.title = 'Noble Diploma with Heraldic Arms'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/noble-diploma-heraldic-arms.svg'
  );

update auctions set
  title = 'Early 20th Century Trade License',
  description = 'Municipal document with multiple signatures and the original letterhead.',
  provenance = 'Acquired from a notary archive lot.'
where title = 'Autorizatie comerciala de inceput de secol XX';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/early-20th-century-trade-license.svg', 0
from auctions a
where a.title = 'Early 20th Century Trade License'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/early-20th-century-trade-license.svg'
  );

update auctions set
  title = 'Antique Map of Moldavia',
  description = 'Hand-colored engraving with wide margins and an ornamental cartouche.',
  provenance = 'Collected in Belgium and imported in 1998.'
where title = 'Harta veche a Moldovei';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/antique-map-of-moldavia.svg', 0
from auctions a
where a.title = 'Antique Map of Moldavia'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/antique-map-of-moldavia.svg'
  );

update auctions set
  title = 'School Atlas of Historical Geography',
  description = 'Complete atlas with color plates and the original binding.',
  provenance = 'Private library of a university professor.'
where title = 'Atlas scolar de geografie istorica';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/school-atlas-historical-geography.svg', 0
from auctions a
where a.title = 'School Atlas of Historical Geography'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/school-atlas-historical-geography.svg'
  );

update auctions set
  title = 'Urban Plan of Bucharest',
  description = 'Fold-out city plan with administrative marks and commercial zoning.',
  provenance = 'Archive of a former urban planner.'
where title = 'Plan urbanistic al Bucurestiului';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/urban-plan-of-bucharest.svg', 0
from auctions a
where a.title = 'Urban Plan of Bucharest'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/urban-plan-of-bucharest.svg'
  );

update auctions set
  title = 'Military Map of Dobruja',
  description = 'Campaign edition with topographic symbols and working folds.',
  provenance = 'From a military-history collection.'
where title = 'Harta militara a Dobrogei';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/military-map-of-dobruja.svg', 0
from auctions a
where a.title = 'Military Map of Dobruja'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/military-map-of-dobruja.svg'
  );

update auctions set
  title = 'Tourist Map of the Carpathians',
  description = 'Early 20th century print with manually marked mountain routes.',
  provenance = 'Acquired from a mixed lot of antique stationery.'
where title = 'Harta turistica a Carpatilor';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/tourist-map-of-the-carpathians.svg', 0
from auctions a
where a.title = 'Tourist Map of the Carpathians'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/tourist-map-of-the-carpathians.svg'
  );

update auctions set
  title = 'Historic Photograph of Calea Victoriei',
  description = 'Albumen print mounted on board with photographer studio inscription.',
  provenance = 'Urban photography holding, Bucharest.'
where title = 'Fotografie istorica a Calea Victoriei';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/historic-photograph-calea-victoriei.svg', 0
from auctions a
where a.title = 'Historic Photograph of Calea Victoriei'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/historic-photograph-calea-victoriei.svg'
  );

update auctions set
  title = 'Studio Portrait of an Interwar Lawyer',
  description = 'Sepia portrait with the studio stamp preserved on the reverse.',
  provenance = 'Family provenance, Ploiesti.'
where title = 'Portret de atelier al unui avocat interbelic';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/studio-portrait-interwar-lawyer.svg', 0
from auctions a
where a.title = 'Studio Portrait of an Interwar Lawyer'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/studio-portrait-interwar-lawyer.svg'
  );

update auctions set
  title = 'Family Album from the Royal Era',
  description = 'Complete family album with 42 photographs and handwritten notes.',
  provenance = 'Kept by the same family to the present day.'
where title = 'Album de familie din perioada Regatului';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/family-album-royal-era.svg', 0
from auctions a
where a.title = 'Family Album from the Royal Era'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/family-album-royal-era.svg'
  );

update auctions set
  title = 'Illustrated Postcard - Sinaia',
  description = 'Travelled postcard with stamp and readable postal cancellation.',
  provenance = 'Recent acquisition from a postcard collection.'
where title = 'Carte postala ilustrata - Sinaia';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/illustrated-postcard-sinaia.svg', 0
from auctions a
where a.title = 'Illustrated Postcard - Sinaia'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/illustrated-postcard-sinaia.svg'
  );

update auctions set
  title = 'Lot of Railway Photographs',
  description = 'Set of eight period photographs featuring locomotives and regional stations.',
  provenance = 'Acquired from an earlier industrial memorabilia auction.'
where title = 'Lot de fotografii feroviare';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/lot-of-railway-photographs.svg', 0
from auctions a
where a.title = 'Lot of Railway Photographs'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/lot-of-railway-photographs.svg'
  );

update auctions set
  title = 'Newspaper on the Union of the Principalities',
  description = 'Historic newspaper issue with political reports and period advertisements.',
  provenance = 'Collection acquired from a regional auction house.'
where title = 'Ziar despre Unirea Principatelor';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/newspaper-union-of-principalities.svg', 0
from auctions a
where a.title = 'Newspaper on the Union of the Principalities'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/newspaper-union-of-principalities.svg'
  );

update auctions set
  title = 'Avant-Garde Literary Magazine',
  description = 'Complete issue with illustrations and distinctive advertisements of the period.',
  provenance = 'Private library focused on literary history.'
where title = 'Revista literara avangardista';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/avant-garde-literary-magazine.svg', 0
from auctions a
where a.title = 'Avant-Garde Literary Magazine'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/avant-garde-literary-magazine.svg'
  );

update auctions set
  title = 'Theatre Poster - Interwar Premiere',
  description = 'Original color-printed poster with minor edge losses from display use.',
  provenance = 'Rescued from a props warehouse.'
where title = 'Afis de teatru - premiera interbelica';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/theatre-poster-interwar-premiere.svg', 0
from auctions a
where a.title = 'Theatre Poster - Interwar Premiere'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/theatre-poster-interwar-premiere.svg'
  );

update auctions set
  title = 'Opera Program with Original Cast',
  description = 'Performance booklet with annotations from a contemporary attendee.',
  provenance = 'Private collection of cultural memorabilia.'
where title = 'Program de opera cu distributie originala';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/opera-program-original-cast.svg', 0
from auctions a
where a.title = 'Opera Program with Original Cast'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/opera-program-original-cast.svg'
  );

update auctions set
  title = 'Illustrated Universal Exposition Supplement',
  description = 'Promotional publication with fold-outs and technical engravings.',
  provenance = 'From the archive of an engineering family.'
where title = 'Supliment ilustrat de expozitie universala';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/illustrated-universal-exposition-supplement.svg', 0
from auctions a
where a.title = 'Illustrated Universal Exposition Supplement'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/illustrated-universal-exposition-supplement.svg'
  );

update auctions set
  title = 'University Medical Thesis',
  description = 'Hand-bound academic work with approvals and official signatures.',
  provenance = 'Decommissioned university medical holding.'
where title = 'Teza universitara de medicina';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/university-medical-thesis.svg', 0
from auctions a
where a.title = 'University Medical Thesis'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/university-medical-thesis.svg'
  );

update auctions set
  title = 'Chemistry Laboratory Notebook',
  description = 'Research notebook with formulas, observations, and authentic work stains.',
  provenance = 'Recovered from a technical institute archive.'
where title = 'Caiet de laborator chimic';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/chemistry-laboratory-notebook.svg', 0
from auctions a
where a.title = 'Chemistry Laboratory Notebook'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/chemistry-laboratory-notebook.svg'
  );

update auctions set
  title = 'Patent for an Optical Device',
  description = 'Technical patent document with appended plates and filing stamps.',
  provenance = 'Secondary lot from a technical-document auction.'
where title = 'Brevet de inventie pentru aparat optic';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/patent-optical-device.svg', 0
from auctions a
where a.title = 'Patent for an Optical Device'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/patent-optical-device.svg'
  );

update auctions set
  title = 'Rare Scientific Publication on Geology',
  description = 'Complete fascicle with fold-out plates and reading annotations.',
  provenance = 'Acquired from a private university library.'
where title = 'Publicatie stiintifica rara despre geologie';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/rare-scientific-publication-geology.svg', 0
from auctions a
where a.title = 'Rare Scientific Publication on Geology'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/rare-scientific-publication-geology.svg'
  );

update auctions set
  title = 'Lot of Typed Academic Lectures',
  description = 'Set of interwar course notes and seminar material in typed form.',
  provenance = 'Archive inherited from a university professor.'
where title = 'Lot de prelegeri academice dactilografiate';

insert into auction_images (auction_id, image_url, display_order)
select a.id, '/demo-images/lot-of-typed-academic-lectures.svg', 0
from auctions a
where a.title = 'Lot of Typed Academic Lectures'
  and not exists (
    select 1
    from auction_images ai
    where ai.auction_id = a.id
      and ai.image_url = '/demo-images/lot-of-typed-academic-lectures.svg'
  );
